name: CI

on:
  push:
    branches: [main, trying, staging]
  pull_request:
    branches: [main, trying, staging]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        # use all supported versions from https://devguide.python.org/versions/
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]

    steps:
      - uses: actions/checkout@v2
      - name: APT update
        run: sudo apt-get update
      - name: Install system dependencies
        run: sudo apt-get install libgeos-dev libproj-dev
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -e .[dev]
      - name: Check Formatting
        run: |
          python -m pycodestyle
      - name: Lint code
        run: |
          python -m pylint geoengine
      - name: Type-check code
        run: |
          python -m mypy geoengine
      - name: Build
        run: python -m build .
      - name: Install test dependencies
        run: |
          pip install -e .[test]
      - name: Lint tests
        run: |
          python -m pylint tests
      - name: Type-check tests
        run: |
          python -m mypy tests
      - name: Test
        run: pytest
      # - name: Publish
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     password: ${{ secrets.pypi_password }}
      #     skip_existing: true
