name: Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install build dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .
      - name: Build
        run: python -m build .
      - name: Test
        run: pytest
      # - name: Publish
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     password: ${{ secrets.pypi_password }}
      #     skip_existing: true
